key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCs77c/2ddpmVSjkJG1rFYB0uxXOjK5asqP5jmEIHtvCeyvTcYU3vJyPj729fygXPbHeDL7wbFIEQMrLB40PL+I+E/i1R+1Htu8iHGFfj+TBAKblAST+8mReaVKnywDN1kxoGFTa93aWM6J8G3i9hKnZ9NeZT+5ream5cFHz4ZWZrC6U4UAiCsFEXLci2iQdDBMWqJHlCvPack7WNygkIC+iSYSE7Bt2FHNxYbmtYnhL2lPaZjUSnhA57/sgAt/AlXC/v8t9VXHnqfxwrxFuvGr391psLeymTk5DEBChhXkKUmahom0s8QMMGgIwrOPKWYwacAyOjV9B+l2no4hGxq9K+rhLtCARz0Geu9FwSYBcXajsnxQpzvXMVTauNTjvk/j1RSzcgs3ADrPwiCTN3dnjTcOc14Oo79pE0MORdlcey1rH1KOWTOJXjRknPqepvsNt8PFBQD3vQ+14hqZWgxxaqTdFx5nKTJoQTapEGb79/7W+l0Dlpqi9GOCVrJc3eE= vn@Home"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.define "server" do |server|
    server.vm.hostname = "server.loc" 
    server.vm.network "private_network", ip: "192.168.56.10", netmask: "255.255.255.0"
    server.vm.network "private_network", ip: "192.168.50.10", netmask: "255.255.255.0" 

    server.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~/.ssh
      echo "#{key}" >> ~/.ssh/authorized_keys
      chmod 700 ~/.ssh
      chmod 600 ~/.ssh/authorized_keys
    SHELL
  end


  # config.vm.provision "ansible" do |ansible|
  #   ansible.playbook = "playbook.yml"
  # end

end
