Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
end

# Vagrant.configure("2") do |config|
#   config.vm.box = "eurolinux-vagrant/centos-stream-9"
# end

# Vagrant.configure("2") do |config|
#   config.vm.box = "centos/stream8"
#   config.vm.box_version = "20210210.0"
# end
