
Vagrant.configure(2) do |config| 
  config.vm.box = "centos/7" 
  config.vm.box_version = "1804.02"

  config.vm.provider "virtualbox" do |v| 
    v.memory = 256 
    v.cpus = 1 
  end

  # config.vm.define "nfss" do |nfss| 
  #   # nfss.vm.hostname = "nfss" 
  # end 

end 
