
key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCs77c/2ddpmVSjkJG1rFYB0uxXOjK5asqP5jmEIHtvCeyvTcYU3vJyPj729fygXPbHeDL7wbFIEQMrLB40PL+I+E/i1R+1Htu8iHGFfj+TBAKblAST+8mReaVKnywDN1kxoGFTa93aWM6J8G3i9hKnZ9NeZT+5ream5cFHz4ZWZrC6U4UAiCsFEXLci2iQdDBMWqJHlCvPack7WNygkIC+iSYSE7Bt2FHNxYbmtYnhL2lPaZjUSnhA57/sgAt/AlXC/v8t9VXHnqfxwrxFuvGr391psLeymTk5DEBChhXkKUmahom0s8QMMGgIwrOPKWYwacAyOjV9B+l2no4hGxq9K+rhLtCARz0Geu9FwSYBcXajsnxQpzvXMVTauNTjvk/j1RSzcgs3ADrPwiCTN3dnjTcOc14Oo79pE0MORdlcey1rH1KOWTOJXjRknPqepvsNt8PFBQD3vQ+14hqZWgxxaqTdFx5nKTJoQTapEGb79/7W+l0Dlpqi9GOCVrJc3eE= vn@Home"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.define "inetRouter" do |inetRouter|
    inetRouter.vm.network "private_network", ip: "192.168.255.1", netmask: "255.255.255.252", virtualbox__intnet: "router-net"
    inetRouter.vm.network "private_network", ip: "192.168.50.10", netmask: "255.255.255.0"

    inetRouter.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~/.ssh
      echo "#{key}" >> ~/.ssh/authorized_keys
      chmod 700 ~/.ssh
      chmod 600 ~/.ssh/authorized_keys
    SHELL

  end

  config.vm.define "centralRouter" do |centralRouter|
    centralRouter.vm.network "private_network",  ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"
    centralRouter.vm.network "private_network", ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"
    centralRouter.vm.network "private_network", ip: '192.168.0.33', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"
    centralRouter.vm.network "private_network", ip: '192.168.0.65', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mgt-net"
    centralRouter.vm.network "private_network", ip: '192.168.255.9', adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "office1-central"
    centralRouter.vm.network "private_network", ip: '192.168.255.5', adapter: 7, netmask: "255.255.255.252", virtualbox__intnet: "office2-central"
    centralRouter.vm.network "private_network", ip: '192.168.50.11', adapter: 8, netmask: "255.255.255.0"

    centralRouter.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~/.ssh
      echo "#{key}" >> ~/.ssh/authorized_keys
      chmod 700 ~/.ssh
      chmod 600 ~/.ssh/authorized_keys
    SHELL

  end

  config.vm.define "centralServer" do |centralServer|
    centralServer.vm.network "private_network", ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"
    centralServer.vm.network "private_network", ip: '192.168.50.12', adapter: 3, netmask: "255.255.255.0"

    centralServer.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~/.ssh
      echo "#{key}" >> ~/.ssh/authorized_keys
      chmod 700 ~/.ssh
      chmod 600 ~/.ssh/authorized_keys
    SHELL

  end

  config.vm.define "office1Router" do |office1Router|
    office1Router.vm.network "private_network", ip: "192.168.255.10", adapter:  2, netmask: "255.255.255.252", virtualbox__intnet: "office1-central"
    office1Router.vm.network "private_network", ip: "192.168.2.1", adapter:  3, netmask: "255.255.255.192", virtualbox__intnet: "dev1-net"
    office1Router.vm.network "private_network", ip: "192.168.2.65", adapter:  4, netmask: "255.255.255.192", virtualbox__intnet: "test1-net"
    office1Router.vm.network "private_network", ip: "192.168.2.129", adapter:  5, netmask: "255.255.255.192", virtualbox__intnet: "managers-net"
    office1Router.vm.network "private_network", ip: "192.168.2.193", adapter:  6, netmask: "255.255.255.192", virtualbox__intnet: "office1-net"
    office1Router.vm.network "private_network", ip: "192.168.50.20", adapter:  7, netmask: "255.255.255.0"


    office1Router.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~/.ssh
      echo "#{key}" >> ~/.ssh/authorized_keys
      chmod 700 ~/.ssh
      chmod 600 ~/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "office1Server" do |office1Server|
    office1Server.vm.network "private_network", ip: "192.168.2.130", adapter:  2, netmask: "255.255.255.192", virtualbox__intnet: "managers-net"
    office1Server.vm.network "private_network", ip: "192.168.50.21", adapter:  3, netmask: "255.255.255.0"

    office1Server.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~/.ssh
      echo "#{key}" >> ~/.ssh/authorized_keys
      chmod 700 ~/.ssh
      chmod 600 ~/.ssh/authorized_keys
    SHELL
  end
  
  config.vm.define "office2Router" do |office2Router|
    office2Router.vm.network "private_network", ip: "192.168.255.6", adapter:  2, netmask: "255.255.255.252", virtualbox__intnet: "office2-central"
    office2Router.vm.network "private_network", ip: "192.168.1.1", adapter:  3, netmask: "255.255.255.128", virtualbox__intnet: "dev2-net"
    office2Router.vm.network "private_network", ip: "192.168.1.129", adapter:  4, netmask: "255.255.255.192", virtualbox__intnet: "test2-net"
    office2Router.vm.network "private_network", ip: "192.168.1.193", adapter:  5, netmask: "255.255.255.192", virtualbox__intnet: "office2-net"
    office2Router.vm.network "private_network", ip: "192.168.50.30", adapter:  6, netmask: "255.255.255.0"

    office2Router.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~/.ssh
      echo "#{key}" >> ~/.ssh/authorized_keys
      chmod 700 ~/.ssh
      chmod 600 ~/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "office2Server" do |office2Server|
    office2Server.vm.network "private_network", ip: "192.168.1.2", adapter:  2, netmask: "255.255.255.128", virtualbox__intnet: "dev2-net"
    office2Server.vm.network "private_network", ip: "192.168.50.31", adapter:  3, netmask: "255.255.255.0"


    office2Server.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~/.ssh
      echo "#{key}" >> ~/.ssh/authorized_keys
      chmod 700 ~/.ssh
      chmod 600 ~/.ssh/authorized_keys
    SHELL
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end


end




