key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCs77c/2ddpmVSjkJG1rFYB0uxXOjK5asqP5jmEIHtvCeyvTcYU3vJyPj729fygXPbHeDL7wbFIEQMrLB40PL+I+E/i1R+1Htu8iHGFfj+TBAKblAST+8mReaVKnywDN1kxoGFTa93aWM6J8G3i9hKnZ9NeZT+5ream5cFHz4ZWZrC6U4UAiCsFEXLci2iQdDBMWqJHlCvPack7WNygkIC+iSYSE7Bt2FHNxYbmtYnhL2lPaZjUSnhA57/sgAt/AlXC/v8t9VXHnqfxwrxFuvGr391psLeymTk5DEBChhXkKUmahom0s8QMMGgIwrOPKWYwacAyOjV9B+l2no4hGxq9K+rhLtCARz0Geu9FwSYBcXajsnxQpzvXMVTauNTjvk/j1RSzcgs3ADrPwiCTN3dnjTcOc14Oo79pE0MORdlcey1rH1KOWTOJXjRknPqepvsNt8PFBQD3vQ+14hqZWgxxaqTdFx5nKTJoQTapEGb79/7W+l0Dlpqi9GOCVrJc3eE= vn@Home"


Vagrant.configure(2) do |config|

  config.vm.define "inetRouter" do |client|
    client.vm.box = "centos/7" 
    client.vm.box_version = "2004.01" 

    client.vm.hostname = "inetRouter"
    client.vm.network "private_network", ip: "192.168.255.1", netmask: "255.255.255.252", virtualbox__intnet: "router-net"
    client.vm.network "private_network", auto_config: false, virtualbox__intnet: "router-net"
    client.vm.network "private_network", auto_config: false, virtualbox__intnet: "router-net"
    client.vm.network "private_network", ip: "192.168.56.10", adapter: 8

    client.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
    SHELL

    client.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~/.ssh
      echo "#{key}" >> ~/.ssh/authorized_keys
      chmod 700 ~/.ssh
      chmod 600 ~/.ssh/authorized_keys
    SHELL

  end

  config.vm.define "centralRouter" do |client|
    client.vm.box = "centos/7" 
    client.vm.box_version = "2004.01" 
    client.vm.hostname = "centralRouter"
    client.vm.network "private_network", auto_config: false, virtualbox__intnet: "router-net"
    client.vm.network "private_network", auto_config: false, virtualbox__intnet: "router-net"
    client.vm.network "private_network", ip: "192.168.255.2", adapter: 5, netmask: "255.255.255.252", virtualbox__intnet: "router-net"
    client.vm.network "private_network", ip: "192.168.255.9", adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "office1-central"
    client.vm.network "private_network", ip: "192.168.56.11", adapter: 8

    client.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
    SHELL
    
    client.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~/.ssh
      echo "#{key}" >> ~/.ssh/authorized_keys
      chmod 700 ~/.ssh
      chmod 600 ~/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "office1Router" do |client|
    client.vm.box = "centos/7" 
    client.vm.box_version = "2004.01" 
    client.vm.hostname = "office1Router"
    client.vm.network "private_network", auto_config: false, virtualbox__intnet: "router-net"
    client.vm.network "private_network", auto_config: false, virtualbox__intnet: "router-net"
    client.vm.network "private_network", ip: "192.168.255.10", adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "office1-central"
    client.vm.network "private_network", ip: "192.168.56.20", adapter: 8

    client.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
    SHELL
    
    client.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~/.ssh
      echo "#{key}" >> ~/.ssh/authorized_keys
      chmod 700 ~/.ssh
      chmod 600 ~/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "testClient1" do |client|
    client.vm.box = "centos/7" 
    client.vm.box_version = "2004.01" 
    client.vm.hostname = "testClient1"
    client.vm.network "private_network", auto_config: false, virtualbox__intnet: "testLAN"
    client.vm.network "private_network", ip: "192.168.56.21", adapter: 8

    client.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
    SHELL
    
    client.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~/.ssh
      echo "#{key}" >> ~/.ssh/authorized_keys
      chmod 700 ~/.ssh
      chmod 600 ~/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "testServer1" do |client|
    client.vm.box = "centos/7" 
    client.vm.box_version = "2004.01" 
    client.vm.hostname = "testServer1"
    client.vm.network "private_network", auto_config: false, virtualbox__intnet: "testLAN"
    client.vm.network "private_network", ip: "192.168.56.22", adapter: 8

    client.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
    SHELL
    
    client.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~/.ssh
      echo "#{key}" >> ~/.ssh/authorized_keys
      chmod 700 ~/.ssh
      chmod 600 ~/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "testClient2" do |client|
    client.vm.box = "ubuntu/jammy64"
    client.vm.hostname = "testClient2"
    client.vm.network "private_network", auto_config: false, virtualbox__intnet: "testLAN"
    client.vm.network "private_network", ip: "192.168.56.31", adapter: 8

    client.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
    SHELL
    
    client.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~/.ssh
      echo "#{key}" >> ~/.ssh/authorized_keys
      chmod 700 ~/.ssh
      chmod 600 ~/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "testServer2" do |client|
    client.vm.box = "ubuntu/jammy64"
    client.vm.hostname = "testServer2"
    client.vm.network "private_network", auto_config: false, virtualbox__intnet: "testLAN"
    client.vm.network "private_network", ip: "192.168.56.32", adapter: 8

    client.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
    SHELL
    
    client.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~/.ssh
      echo "#{key}" >> ~/.ssh/authorized_keys
      chmod 700 ~/.ssh
      chmod 600 ~/.ssh/authorized_keys
    SHELL
  end

end


