Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204" # Use Ubuntu 18.04 LTS

  # First machine
  config.vm.define "machine1" do |machine1|
    machine1.vm.hostname = "web"
    machine1.vm.network "private_network", ip: "192.168.56.10"
  end

  # Second machine
  config.vm.define "machine2" do |machine2|
    machine2.vm.hostname = "log"
    machine2.vm.network "private_network", ip: "192.168.56.15"
  end

  # Configure the provider (VirtualBox in this case)
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
end
