---
- hosts: router1, router2, router3
  become: yes
  tasks:
    - name: set up forward packages across outers
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present
    - name: turn off async 
      sysctl:
        name: net.ipv4.conf.all.rp_filter
        value: '0'
        state: present

    - name: install base tools
      apt:
        name:
          - vim
          - traceroute
          - tcpdump
          - net-tools
        state: present
        update_cache: true

    - name: Stop and disable UFW
      systemd:
        name: ufw
        state: stopped
        enabled: no
  
    - name: Add GPG key for FRR
      apt_key:
        url: https://deb.frrouting.org/frr/keys.asc

    - name: Add FRR repository
      lineinfile:
        path: /etc/apt/sources.list.d/frr.list
        line: deb https://deb.frrouting.org/frr {{ ansible_lsb.codename }} frr-stable
        create: yes

    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install FRR and FRR Python tools
      apt:
        name:
          - frr
          - frr-pythontools
        state: present

    - name: Ensure zebra is enabled
      ansible.builtin.lineinfile:
        path: /etc/frr/daemons
        line: "zebra=yes"
        regexp: '^zebra=.*'
        create: yes

    - name: Ensure ospfd is enabled
      ansible.builtin.lineinfile:
        path: /etc/frr/daemons
        line: "ospfd=yes"
        regexp: '^ospfd=.*'
        create: yes

- hosts: router1
  become: yes
  tasks:
    - name: Copy 
      copy:
        src: ./frr-router1.conf
        dest: /etc/frr/frr.conf
        owner: frr
        group: frr
        mode: 0640

- hosts: router2
  become: yes
  tasks:
    - name: Copy 
      copy:
        src: ./frr-router2.conf
        dest: /etc/frr/frr.conf
        owner: frr
        group: frr
        mode: 0640

- hosts: router3
  become: yes
  tasks:
    - name: Copy 
      copy:
        src: ./frr-router3.conf
        dest: /etc/frr/frr.conf
        owner: frr
        group: frr
        mode: 0640


- hosts: router1, router2, router3
  become: yes
  tasks:
    - name: Restart FRR service
      ansible.builtin.systemd:
        name: frr.service
        state: restarted
