---
- hosts: server
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install openvpn
      apt:
        name: openvpn
        state: present

    - name: Install iperf3
      apt:
        name: iperf3
        state: present

    - name: Copy server.conf
      copy:
        src: ./server.conf
        dest: /etc/openvpn/server.conf
        owner: root
        group: root
        mode: 0644
    
    - name: Check if OpenVPN static key exists
      stat:
        path: /etc/openvpn/static.key
      register: static_key_status

    - name: Generate OpenVPN static key
      ansible.builtin.shell: "openvpn --genkey --secret /etc/openvpn/static.key"
      when: not static_key_status.stat.exists


    - name: Copy key file to local
      fetch:
        src: /etc/openvpn/static.key
        dest: ./

    - name: Copy service file
      copy:
        src: ./openvpn@.service
        dest: /etc/systemd/system/openvpn@.service
        owner: root
        group: root
        mode: 0644

    - name: Start OpenVPN service
      ansible.builtin.systemd:
        name: openvpn@server
        state: started
        enabled: yes



- hosts: client
  become: yes
  tasks:
    - name: Copy key file 
      copy:
        src: ./static.key 
        dest: /etc/openvpn/static.key
        force: true

    - name: Copy server.conf
      copy:
        src: ./client-server.conf
        dest: /etc/openvpn/server.conf
        owner: root
        group: root
        mode: 0644
 
    - name: Copy service file
      copy:
        src: ./client-openvpn@.service
        dest: /etc/systemd/system/openvpn@.service
        owner: root
        group: root
        mode: 0644

    - name: Start OpenVPN service
      ansible.builtin.systemd:
        name: openvpn@server
        state: started
        enabled: yes
